apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-certpl-lifetime
  namespace: ocm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS DataSecurity
    policy.open-cluster-management.io/controls: PR.DS-2 Data-in-transit
spec:
  complianceType: musthave
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: CertificatePolicy # cert management lifetime
        metadata:
          name: policy-cert-lifetime
        spec:
          namespaceSelector:
            include: ["lifetime"]
            exclude: []
          remediationAction: inform
          severity: low
          minimumDuration: 300h
          maximumDuration: 9528h
          maximumCADuration: 87600h
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-cert-lifetime
  namespace: ocm-policies
placementRef:
  name: placement-policy-cert-lifetime
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-cert-lifetime
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-cert-lifetime
  namespace: ocm-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: environment
      operator: In
      values:
      - dev
